import Head from 'next/head'
import Link from 'next/link'
import { BsCodeSquare, BsFillMoonStarsFill } from 'react-icons/bs'
import { AiOutlineMenu } from 'react-icons/ai'
import { useState } from 'react'
import { Hero } from '@/components/Hero'
import { About } from '@/components/About'
import { Skills } from '@/components/Skills'
import { Projects } from '@/components/Projects'
import { Contact } from '@/components/Contact'
import { Footer } from '@/components/Footer'

export default function Home() {
    const [darkMode, setDarkMode] = useState(true)

    return (
        <div className={darkMode ? 'dark bg-bg-clear' : 'bg-bg-dark'}>
            <Head>
                <title>Ps3udoDev</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="fixed top-0 bg-bg-dark dark:bg-bg-clear flex w-screen h-16 justify-center z-10">
                <nav className='border-b-[1px] flex items-center justify-between max-w-6xl w-full mx-6 md:mx-0'>
                    <h1 className='text-links-dark dark:text-links-clear text-2xl'>
                        <Link href='/' className='flex items-center'>
                            <BsCodeSquare className='text-text-dark dark:text-text-clear mr-3' />
                            Ps3udo<span className='text-text-dark dark:text-text-clear'>Dev</span>
                        </Link>
                    </h1>
                    <div className='nav-links duration-500 md:static absolute md:min-h-fit bg-text-clear dark:bg-bg-clear min-h-[30vh] top-16 md:w-auto w-full flex items-center px-6 left-[-100%]'>
                        <ul className='text-text-dark font-bold dark:text-text-clear flex flex-col md:flex-row md:items-center md:gap-6 gap-9'>
                            <li className='transition hover:text-links-dark dark:hover:text-links-clear'>
                                <Link href='#about'>About Me</Link>
                            </li>
                            <li className='transition hover:text-links-dark dark:hover:text-links-clear'>
                                <Link href='#skills'>Skills</Link>
                            </li>
                            <li className='transition hover:text-links-dark dark:hover:text-links-clear'>
                                <Link href='#projects'>Projects</Link>
                            </li>
                            <li className='transition hover:text-links-dark dark:hover:text-links-clear'>
                                <Link href='#contact'>Contact Me</Link>
                            </li>
                        </ul>
                    </div>
                    <div className='flex items-center gap-6'>
                        <BsFillMoonStarsFill
                            onClick={() => setDarkMode(!darkMode)}
                            className='text-bg-clear dark:text-text-clear cursor-pointer text-2xl'
                        />
                        <AiOutlineMenu
                            onClick={() => {
                                const nav = document.querySelector('.nav-links')
                                nav.classList.toggle('left-[0%]')
                            }}
                            className='text-bg-clear dark:text-text-clear cursor-pointer text-2xl md:hidden'
                        />
                    </div>
                </nav>
            </header>
            <main className='m-auto w-full max-w-6xl top-16'>
                <Hero theme={darkMode} />
                <About theme={darkMode} />
                <Skills theme={darkMode} />
                <Projects theme={darkMode} />
                <Contact theme={darkMode} />
                <Footer theme={darkMode} />
            </main>
        </div>
    )
}
